In [1]:
import pandas as pd

In [4]:
data = pd.read_csv("./movie_metadata.csv")

In [5]:
data.country

0          USA
1          USA
2           UK
3          USA
4          NaN
         ...
5038    Canada
5039       USA
5040       USA
5041       USA
5042       USA
Name: country, Length: 5043, dtype: object

In [7]:
data['country'].fillna("") # fillna() 用XX来填充空值

0          USA
1          USA
2           UK
3          USA
4
         ...
5038    Canada
5039       USA
5040       USA
5041       USA
5042       USA
Name: country, Length: 5043, dtype: object

In [10]:
# 使用均值来填充电影时长字段的空值
data.duration = data.duration.fillna(data.duration.mean())

In [11]:
data.duration

0       178.000000
1       169.000000
2       148.000000
3       164.000000
4       107.201074
           ...
5038     87.000000
5039     43.000000
5040     76.000000
5041    100.000000
5042     90.000000
Name: duration, Length: 5043, dtype: float64

In [12]:
data['title_year'].isnull().value_counts()

False    4935
True      108
Name: title_year, dtype: int64

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5043 entries, 0 to 5042
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   color                      5024 non-null   object
 1   director_name              4939 non-null   object
 2   num_critic_for_reviews     4993 non-null   float64
 3   duration                   5043 non-null   float64
 4   director_facebook_likes    4939 non-null   float64
 5   actor_3_facebook_likes     5020 non-null   float64
 6   actor_2_name               5030 non-null   object
 7   actor_1_facebook_likes     5036 non-null   float64
 8   gross                      4159 non-null   float64
 9   genres                     5043 non-null   object
 10  actor_1_name               5036 non-null   object
 11  movie_title                5043 non-null   object
 12  num_voted_users            5043 non-null   int64
 13  cast_total_facebook_likes  5043 non-null   int64
 14  actor_3_name               5020 non-null   object
 15  facenumber_in_poster       5030 non-null   float64
 16  plot_keywords              4890 non-null   object
 17  movie_imdb_link            5043 non-null   object
 18  num_user_for_reviews       5022 non-null   float64
 19  language                   5031 non-null   object
 20  country                    5038 non-null   object
 21  content_rating             4740 non-null   object
 22  budget                     4551 non-null   float64
 23  title_year                 4935 non-null   float64
 24  actor_2_facebook_likes     5030 non-null   float64
 25  imdb_score                 5043 non-null   float64
 26  aspect_ratio               4714 non-null   float64
 27  movie_facebook_likes       5043 non-null   int64
dtypes: float64(13), int64(3), object(12)
memory usage: 1.1+ MB

In [14]:
data.movie_title

0                                                 Avatar
1               Pirates of the Caribbean: At World's End
2                                                Spectre
3                                  The Dark Knight Rises
4       Star Wars: Episode VII - The Force Awakens    ...
                              ...
5038                             Signed Sealed Delivered
5039                           The Following
5040                                A Plague So Pleasant
5041                                    Shanghai Calling
5042                                   My Date with Drew
Name: movie_title, Length: 5043, dtype: object

In [16]:
data

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.000000,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.000000,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.000000,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.000000,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,107.201074,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Color,Scott Smith,1.0,87.000000,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
5039,Color,NaN,43.0,43.000000,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
5040,Color,Benjamin Roberds,13.0,76.000000,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
5041,Color,Daniel Hsia,14.0,100.000000,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
5042,Color,Jon Gunn,43.0,90.000000,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [18]:
s1 = data.movie_title.str.strip()

In [19]:
s1.str.upper()

0                                           AVATAR
1         PIRATES OF THE CARIBBEAN: AT WORLD'S END
2                                          SPECTRE
3                            THE DARK KNIGHT RISES
4       STAR WARS: EPISODE VII - THE FORCE AWAKENS
                           ...
5038                       SIGNED SEALED DELIVERED
5039                                 THE FOLLOWING
5040                          A PLAGUE SO PLEASANT
5041                              SHANGHAI CALLING
5042                             MY DATE WITH DREW
Name: movie_title, Length: 5043, dtype: object

In [30]:
s3 = data.director_name.str.strip()

In [32]:
data[["first_name","last_name","col1","col2"]] = s3.str.split(" ",expand=True)

In [33]:
data

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,first_name,last_name,col1,col2
0,Color,James Cameron,723.0,178.000000,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,237000000.0,2009.0,936.0,7.9,1.78,33000,James,Cameron,None,None
1,Color,Gore Verbinski,302.0,169.000000,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,300000000.0,2007.0,5000.0,7.1,2.35,0,Gore,Verbinski,None,None
2,Color,Sam Mendes,602.0,148.000000,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,245000000.0,2015.0,393.0,6.8,2.35,85000,Sam,Mendes,None,None
3,Color,Christopher Nolan,813.0,164.000000,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,250000000.0,2012.0,23000.0,8.5,2.35,164000,Christopher,Nolan,None,None
4,NaN,Doug Walker,NaN,107.201074,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,12.0,7.1,NaN,0,Doug,Walker,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Color,Scott Smith,1.0,87.000000,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,NaN,2013.0,470.0,7.7,NaN,84,Scott,Smith,None,None
5039,Color,NaN,43.0,43.000000,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,NaN,NaN,593.0,7.5,16.00,32000,NaN,NaN,None,None
5040,Color,Benjamin Roberds,13.0,76.000000,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,1400.0,2013.0,0.0,6.3,NaN,16,Benjamin,Roberds,None,None
5041,Color,Daniel Hsia,14.0,100.000000,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,NaN,2012.0,719.0,6.3,2.35,660,Daniel,Hsia,None,None
5042,Color,Jon Gunn,43.0,90.000000,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,1100.0,2004.0,23.0,6.6,1.85,456,Jon,Gunn,None,None

In [34]:
data[data.col1.isnull()^ True]

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,first_name,last_name,col1,col2
52,Color,Guillermo del Toro,575.0,131.0,0.0,919.0,Clifton Collins Jr.,16000.0,101785482.0,Action|Adventure|Sci-Fi,...,190000000.0,2013.0,968.0,7.0,1.85,83000,Guillermo,del,Toro,None
139,Color,Jennifer Yuh Nelson,284.0,90.0,90.0,15.0,Gary Oldman,11000.0,165230261.0,Action|Adventure|Animation|Comedy|Family,...,150000000.0,2011.0,10000.0,7.3,2.35,20000,Jennifer,Yuh,Nelson,None
140,Color,M. Night Shyamalan,280.0,103.0,0.0,346.0,Noah Ringer,1000.0,131564731.0,Action|Adventure|Family|Fantasy,...,150000000.0,2010.0,756.0,4.2,2.35,18000,M.,Night,Shyamalan,None
168,Color,Jon M. Chu,351.0,122.0,209.0,934.0,Dwayne Johnson,17000.0,122512052.0,Action|Adventure|Sci-Fi|Thriller,...,130000000.0,2013.0,12000.0,5.8,2.35,42000,Jon,M.,Chu,None
179,Color,Alejandro G. Iñárritu,556.0,156.0,0.0,733.0,Tom Hardy,29000.0,183635922.0,Adventure|Drama|Thriller|Western,...,135000000.0,2015.0,27000.0,8.1,2.35,190000,Alejandro,G.,Iñárritu,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4997,Color,David Gordon Green,75.0,90.0,234.0,15.0,Eddie Rouse,552.0,241816.0,Drama,...,42000.0,2000.0,61.0,7.5,2.35,451,David,Gordon,Green,None
5002,Color,Collin Joseph Neal,7.0,75.0,14.0,130.0,Thomas Brophy,252.0,NaN,Horror|Thriller,...,50000.0,2012.0,132.0,3.7,2.35,225,Collin,Joseph,Neal,None
5003,Color,Bradley Rust Gray,61.0,79.0,2.0,20.0,Mark Rendall,962.0,24705.0,Drama,...,NaN,2009.0,72.0,6.3,NaN,377,Bradley,Rust,Gray,None
5031,Color,Thomas L. Phillips,13.0,82.0,120.0,84.0,Joe Coffey,785.0,NaN,Comedy|Horror|Thriller,...,200000.0,2012.0,98.0,5.4,16.00,424,Thomas,L.,Phillips,None
5034,Color,Neill Dela Llana,35.0,80.0,0.0,0.0,Edgar Tancangco,0.0,70071.0,Thriller,...,7000.0,2005.0,0.0,6.3,NaN,74,Neill,Dela,Llana,None